### ISSUE TITLE
Remove "Adhesion"

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/PyNUCOS#18]
Not sure we need it, but it certainly shouldn't have "grams force" and the like.

Maybe put Pressure in there -- we don't have a use case, but for completeness' sake?

**Comment by JamesMakela-NOAA** [comment]
The Env Canada datasheet clearly has Adhesion as one of its data points
Are you suggesting that we use a generic Pressure measurement to handle it?

**Comment by ChrisBarker-NOAA** [comment]
no -- see the gitLab issue for AdiosDB.

The issue is that the Env CA "adhesion" is NOT this unit.

Some googling indicates that adhesion is measured in different ways, with different units. Some of which are essentially pressure units, but not all.

Pressure is force per unit area: i.e. lbs/sq in or Pa/sq m -- those are fine, if not required for our use case.

**Comment by ChrisBarker-NOAA** [comment]
done
