### ISSUE TITLE
Remove Special Exceptions?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/PyNUCOS#3]
I wrote that code a long time ago, and did the whioe hierarchy of exceptions thing.

But really, they are all ValueErrors -- not need for special exceptions. I think we should remove them.

But is any user code specifically catching them?

@jay-hennen: is any of your code doing that?

**Comment by jay-hennen** [comment]
Yes, I believe my code is catching them. That can be fixed easily enough, however. If the special exceptions are to be removed, it shouldn't be a big deal.

**Comment by ChrisBarker-NOAA** [comment]
OK.

I've spent WAY too much time cleaning this up, but let's keep this issue
here for when we next need to touch it.

BTW, the special Exceptions now derive from ValueError, so client code
should be able to catch that instead to be future proof,

Unless you are actually distinguishing between the errors in a useful way.

-CHB

Sent from my iPhone

On Jun 29, 2016, at 3:10 PM, jay-hennen <notifications@github.com> wrote:

Yes, I believe my code is catching them. That can be fixed easily enough,
however. If the special exceptions are to be removed, it shouldn't be a big
deal.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NOAA-ORR-ERD/PyNUCOS/issues/3#issuecomment-229504593>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA38YMfR3ksbPiOm25q7Za5y7aTaoPaDks5qQu1PgaJpZM4JBm-T>
.

**Comment by ChrisBarker-NOAA** [comment]
this is good enough now.
